const products = [
  {
    id: 1,
    name: "Midnight Bloom Eau de Parfum",
    price: 33600,
    oldPrice: 42000,
    discount: 20,
    category: "Perfumes",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800",
    rating: 4.9,
    stock: 15,
    variants: ["30ml", "50ml", "100ml"],
    description: "A sensual, dark floral fragrance with notes of black orchid, vanilla, and warm sandalwood.",
    isFeatured: true,
    isTrending: true
  },
  {
    id: 2,
    name: "Silk Slip Evening Dress",
    price: 68600,
    oldPrice: null,
    discount: 0,
    category: "Garments",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    stock: 8,
    variants: ["XS", "S", "M", "L", "XL"],
    description: "Elegant 100% pure silk slip dress featuring a draped neckline and high slit.",
    isFeatured: true,
    isTrending: false
  },
  {
    id: 3,
    name: "Lumina Gold Strappy Heels",
    price: 51800,
    oldPrice: 61600,
    discount: 15,
    category: "Sandals",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    stock: 12,
    variants: ["36", "37", "38", "39", "40", "41"],
    description: "Premium leather strappy stiletto heels in metallic gold finish. Perfect for exclusive events.",
    isFeatured: false,
    isTrending: true
  },
  {
    id: 4,
    name: "Velvet Matte Lipstick Set",
    price: 23800,
    oldPrice: 28000,
    discount: 15,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=800",
    rating: 4.9,
    stock: 25,
    variants: ["Ruby Red", "Dusty Rose", "Nude Peach"],
    description: "Highly pigmented, long-lasting matte lipsticks infused with hydrating oils.",
    isFeatured: true,
    isTrending: true
  },
  {
    id: 5,
    name: "18K Rose Gold Minimalist Necklace",
    price: 98000,
    oldPrice: null,
    discount: 0,
    category: "Jewelry",
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&q=80&w=800",
    rating: 5.0,
    stock: 5,
    variants: ["16 inch", "18 inch", "20 inch"],
    description: "A timeless, elegant 18K solid rose gold chain with a delicate floating diamond pendant.",
    isFeatured: true,
    isTrending: false
  },
  {
    id: 6,
    name: "Cashmere Wrap Sweater",
    price: 54600,
    oldPrice: 70000,
    discount: 22,
    category: "Garments",
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=800",
    rating: 4.6,
    stock: 20,
    variants: ["S", "M", "L"],
    description: "Ultra-soft premium Mongolian cashmere wrap sweater in neutral beige.",
    isFeatured: false,
    isTrending: true
  },
  {
    id: 7,
    name: "Flawless Base Foundation",
    price: 18200,
    oldPrice: null,
    discount: 0,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    stock: 40,
    variants: ["Fair", "Light", "Medium", "Tan", "Deep"],
    description: "A lightweight, buildable foundation that leaves a natural, radiant finish.",
    isFeatured: false,
    isTrending: true
  },
  {
    id: 8,
    name: "Oceanic Pearl Earrings",
    price: 40600,
    oldPrice: null,
    discount: 0,
    category: "Jewelry",
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    stock: 7,
    variants: ["Gold Plated", "Silver Plated"],
    description: "Genuine freshwater pearls set in minimalist gold or silver drop clasps.",
    isFeatured: true,
    isTrending: false
  },
  {
    id: 9,
    name: "Blush Pink Block Sandals",
    price: 30800,
    oldPrice: 36400,
    discount: 15,
    category: "Sandals",
    image: "https://images.unsplash.com/photo-1562183241-b937e95585b6?auto=format&fit=crop&q=80&w=800",
    rating: 4.5,
    stock: 18,
    variants: ["36", "37", "38", "39", "40"],
    description: "Comfortable and chic block heel sandals with a soft suede finish.",
    isFeatured: false,
    isTrending: false
  },
  {
    id: 10,
    name: "Aura Signature Perfume",
    price: 39200,
    oldPrice: null,
    discount: 0,
    category: "Perfumes",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800",
    rating: 4.9,
    stock: 10,
    variants: ["50ml", "100ml"],
    description: "A fresh and luminous blend of bergamot, jasmine, and white musk.",
    isFeatured: true,
    isTrending: true
  },
  {
    id: 11,
    name: "Tailored Linen Blazer",
    price: 58800,
    oldPrice: 78400,
    discount: 25,
    category: "Garments",
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&q=80&w=800",
    rating: 4.8,
    stock: 14,
    variants: ["XS", "S", "M", "L"],
    description: "A sharp, structured linen blazer perfect for sophisticated office wear or casual outings.",
    isFeatured: false,
    isTrending: true
  },
  {
    id: 12,
    name: "Radiant Glow Highlighter",
    price: 12600,
    oldPrice: null,
    discount: 0,
    category: "Cosmetics",
    image: "https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&q=80&w=800",
    rating: 4.7,
    stock: 35,
    variants: ["Champagne", "Rose Gold", "Bronze"],
    description: "A finely milled powder highlighter that delivers a striking, glass-skin glow.",
    isFeatured: false,
    isTrending: false
  }
];
